# Generated by Django 5.1.2 on 2024-10-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('brasao', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('sobre', models.TextField()),
                ('avatar', models.ImageField(upload_to='static/img')),
                ('is_admin', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Seguidor_seguindo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguidor', to='usuarios.usuario')),
                ('id_seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_seguindo', to='usuarios.usuario')),
            ],
        ),
    ]
