# Generated by Django 5.1.2 on 2024-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='usuarios/default_avatar.png', upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
    ]
