# Generated by Django 5.1.2 on 2024-10-16 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curtidas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revisão',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texto',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texto',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacoes.classificação_indicativa'),
        ),
        migrations.AddField(
            model_name='texto',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacoes.genero'),
        ),
        migrations.AddField(
            model_name='revisão',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacoes.texto'),
        ),
        migrations.AddField(
            model_name='curtidas',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacoes.texto'),
        ),
    ]
